### ISSUE TITLE
Day 2: Fix RData path

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified#10]
https://github.com/umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified/blob/495c6db80a913d033819dbe69a85f5f9abb56e61/Module11X_BonusContent.Rmd#L32

Should be:

```
load("rdata/RunningData_Full.RData")
```

**Comment by dkcoxie** [comment]
Corrected directory structure for rdata in Module 11X
