### ISSUE TITLE
Day 2: Add rdata directory to the block

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified#4]
https://github.com/umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified/blob/495c6db80a913d033819dbe69a85f5f9abb56e61/Module06_DEAnalysisSetup.Rmd#L337-L341

I think you need to add:

```
dir.create('rdata')
```

to this block so that the saving works properly during the knitting.

**Comment by dkcoxie** [comment]
Good catch - updated end code block in Module 06.
