### ISSUE TITLE
Day 2: Forgot geom_point() in exercise solution?

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified#5]
https://github.com/umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified/blob/495c6db80a913d033819dbe69a85f5f9abb56e61/Module09_SampleQCViz.Rmd#L180-L186

In the solution, should it be the following?

```
gp <- ggplot(p.all$data, aes(x = PC1, y = PC2, color = SampleName, shape = CombinatoricGroup)) +
geom_point() + ggtitle(label = as.character('All samples Rlog-Normalized'))
```

Otherwise, it plots the axes and title.

**Comment by dkcoxie** [comment]
Yes, added correction, thank you!
