### ISSUE TITLE
Day 2: Consider simplifying complex plot

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified#6]
https://github.com/umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified/blob/495c6db80a913d033819dbe69a85f5f9abb56e61/Module09_SampleQCViz.Rmd#L190-L205

I like the idea of showing them more of the options to make things bigger, change names of the legend, etc. But I think some components might be too detailed, and might detract from the overall purpose.

For example, I created the `gp` plot from the code the referenced block, and it *mostly* looks the same. Perhaps paring down the complex plot code to the following might allow the learners to focus on some of the important tweaks?

```
gp <- ggplot(p.all$data, aes(x = PC1, y = PC2, color = SampleName, shape = CombinatoricGroup)) +
    scale_shape_manual(values=1:nlevels(CombinatoricGroup), name = 'Combinatoric Group') +
    geom_point(size=2) +
    ggtitle(label = as.character('All samples Rlog-Normalized')) +
    guides(colour=guide_legend(nrow = 12, title = 'Sample')) +
    xlab(p.all$labels[2]) + ylab(p.all$labels[1]) +
    theme_classic(base_size = 10)
```

To my eye, the above code plots something indistinguishable from the more complex code with all the margin adjustments.

**Comment by dkcoxie** [comment]
Great idea - I don't have high expectations of most learners getting to the more detailed plot but agree that simplifying the 'complex' example would be helpful. Thanks for providing an alternative!

**Comment by dkcoxie** [comment]
Updated plot code in Module 09.
