### ISSUE TITLE
Day 2: Fix PC with less variance

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified#7]
https://github.com/umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified/blob/495c6db80a913d033819dbe69a85f5f9abb56e61/Module09_SampleQCViz.Rmd#L246

Looking at the `gp` and `p.raw` plots, I think:

> less variance explained by PC1

should be:

> less variance explained by PC2

**Comment by dkcoxie** [comment]
Mistake has been corrected.
