### ISSUE TITLE
Day 2: Invalid reference to res_WT_anno 

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified#8]
https://github.com/umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified/blob/495c6db80a913d033819dbe69a85f5f9abb56e61/Module11_DEVisualizations.Rmd#L211

Should be:

```
res_WT_DE[which(!is.na(res_WT_DE$padj) & res_WT_DE$padj < 0.05 & abs(res_WT_DE$log2FoldChange) >= log2(1.5)), ]$Call <- TRUE
```

**Comment by dkcoxie** [comment]
Corrected error in Module 11.
