### ISSUE TITLE
Day 2: Incorrect by.x in res_WT_anno

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified#9]
https://github.com/umich-brcf-bioinf/2021-11-15-umich-rnaseq-demystified/blob/495c6db80a913d033819dbe69a85f5f9abb56e61/Module11_DEVisualizations.Rmd#L277

Should be:

```
res_WT_anno <- merge(GeneKey, res_WT_anno, by.x = "ensembl_gene_id", by.y="genes", all.x = FALSE, all.y = TRUE)
```

**Comment by dkcoxie** [comment]
Thank you, errors has been corrected in Module 11
